apiVersion: v1
kind: Service
metadata:
  name: playlists-recommender-system-service
spec:
  selector:
    app: playlists-recommender-system
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 50006
