apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: davineves
  name: project2-pv2-davineves
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: default-storage-class-davineves
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/davineves/project2-pv2
