apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: davineves-model-pvc
  namespace: davineves
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-davineves
  selector:
    matchLabels:
      namespace: davineves
